### ISSUE TITLE
lgogd_uri only supports old versions of LGOGDownloader

### ISSUE THREAD

**Issue by natanprog** [ssokolow/lgogd_uri#21]
```
Traceback (most recent call last):
  File "/usr/local/bin/lgogd_uri", line 9, <module>()
        sys.exit(
            load_entry_point('lgogd-uri==0.1.0.1', 'gui_scripts', 'lgogd_uri')()
        )
  variables: {  'load_entry_point': (  'local',
                          <function load_entry_point at 0x7f6891a645f0>)}
  File "/usr/local/lib/python2.7/dist-packages/lgogd_uri/main.py", line 511, main()
        app.start(vars(opts), args, int(time.time()))
        if app.is_running():
  variables: {  'app.start': (  'local',
                   <bound method Application.start of <lgogd_uri.main.Application at / at 0x7f6889489b10>>),
   'args': ('local', ['gogdownloader://ultima_4/installer_win_en']),
   'int': ('builtin', <type 'int'>),
   'opts': ('local', <Values at 0x7f688948a200: {'verbose': 2, 'quiet': 0}>),
   'time.time': ('global', <built-in function time>),
   'vars': ('builtin', <built-in function vars>)}
  File "/usr/local/lib/python2.7/dist-packages/lgogd_uri/main.py", line 473, start(self=<lgogd_uri.main.Application at />, options={'quiet': 0, 'verbose': 2}, arguments=['gogdownloader://ultima_4/installer_win_en'], timestamp=1509330030)
                self._init_gui()
                self.enqueue_uris(arguments)
                gtk.main()
  variables: {  'arguments': ('local', ['gogdownloader://ultima_4/installer_win_en']),
   'self.enqueue_uris': (  'local',
                           <bound method Application.enqueue_uris of <lgogd_uri.main.Application at / at 0x7f6889489b10>>)}
  File "/usr/local/lib/python2.7/dist-packages/lgogd_uri/main.py", line 290, enqueue_uris(self=<lgogd_uri.main.Application at />, arguments=['gogdownloader://ultima_4/installer_win_en'])
                        is_installer,
                        platforms & PLAT_WIN,
                        platforms & PLAT_LIN,
  variables: {  'PLAT_WIN': ('global', 1), 'platforms': ('local', u'w+l')}
TypeError: unsupported operand type(s) for &: 'unicode' and 'int'
```

**Comment by ssokolow** [comment]
I'm still running an ancient version of lgogdownloader because, when I tried to install a newer version on my brother's machine, it segfaulted... and version `2.25 git d9587e454455` has never let me down.

Amadren has put together a [fork for newer lgogdownloader versions](https://github.com/Amadren/lgogd_uri-mk.II).

In the mean time, I'll leave this open as a reminder to do two things:

1. Detect this case and show an "unsupported lgogdownloader version" message.
2. Install something newer in a VM when I can find the time and update lgogd_uri. (Though I have a lot of much more pressing things to do at the moment so it could take quite a while.)
